

version: 1.0.{build}
skip_tags: true

platform: x64

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      JAVA_HOME: C:\Program Files\Java\jdk12
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

build_script:

- cmd: ./gradlew jlinkZip

artifacts:

- path: build/distributions

  name: Application

deploy:

- provider: GitHub

  tag: ci

  release: TestFX

  auth_token:

    secure: v+ayw++Z5NxyZh19dUH6dTxOv9UArb14sFiAxmR3j1BXelxZD7ebJJV/cJYkTlv0

  artifact: Application

  force_update: true

  on:

    branch: master

