

version: 1.0.{build}

image:

- Ubuntu

- Visual Studio 2019

platform: x64

init:

- ps: >-

    if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2019"){



    $env:JAVA_HOME="C:\Program Files\Java\jdk12"



    }

build_script:

- ps: ./gradlew jlinkZip

artifacts:

- path: build/image.zip

  name: Application

deploy:

- provider: GitHub

  tag: ci

  release: TestFX

  auth_token:

    secure: v+ayw++Z5NxyZh19dUH6dTxOv9UArb14sFiAxmR3j1BXelxZD7ebJJV/cJYkTlv0

  artifact: Application

  on:

    branch: master


